name = "ImageIO"
uuid = "bbb7a0cc-4ad1-4b1c-84de-8cb153b0a391"
authors = ["Ian Butterworth"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
